create table CUSTOMER (CUSTOMERID int primary key, CUSTOMERNAME varchar(20), DATEOFBIRTH DATE, ADDRESS VARCHAR(50), PHONENUMBER VARCHAR(10), LOCKERID VARCHAR(20));
create table LOCKER (LOCKERID VARCHAR(20) primary key, LOCKERTYPE varchar(20), RENT int);
ALTER TABLE CUSTOMER ADD FOREIGN KEY (LOCKERID) REFERENCES LOCKER(LOCKERID);